v0.0.8 - feature add - 2015-##-##
---------------------------------
* added handling of existing files with rootDir for sources
	** added new constructor to AbstractFileInfo and sub classes - (File file, String setRoot)
	** added now method to FileListSource - getSourceAsFileSourceList(String setRoot)
* added setReporter() and setSTG() to Message5WH
* added setSTG() to Abstract_CC and changed rendering to pick it up if set
* added AbstractDirectoryInfo and adapted DirectorySource and DirectoryTarget
	** added class path lookup
* renamed FileLocationOptions to InfoLocationOptions
	** added class path locations for directories
	** FileSource/Target only accept file locations (FS and Resource)
	** DirectorySource/Target only accept directory locations (FS and CP)
* removed Skb_UrlUtils, all those features are now in File/Directory Source/Target
* added emptyPrint to Skb_ConsoleUtils.getNbReader for prompt printing on empty readline results


v0.0.7 - feature add - 2015-07-21
---------------------------------
* added package info with source, loader, target, writer and validator interfaces and classes
* removed utils/Skb_PropertyUtils - now in the property loaders in the info package
* changes to Skb_UrlUtils
	** removed Skb_UrlUtils#getUrlFromResource(String filename), now handled by FileSource
	** removed Skb_UrlUtils#getUrl(Object filename), now handled by FileSource
* changes to Skb_STUtils
	** removed Skb_STUtils#getMissingChunks(...), now handled by STGroupValidator
	** removed Skb_STUtils#getMissingSTArguments(...), now handled by STValidator
	** moved related tests from Test_Skb_STUtils to Test_STValidator and Test_STValidator
	** removed Test_Skb_STUtils then
	** adapted Message5WH and Test_Message5WH accordingly
	** adapted ReportManager accordingly
* changes to the message package
	** created a builder for Message5WH and moved all build methods into that builder
	** cleaned tests and created separate classes for tests
	** added a wrapper for SLF4J FormattingTuple objects (toString needs to do a getMessage for the message object)
	** added new add() methods to the CC_* coin objects to use the new FormattingTuple wrapper



v0.0.6 - feature add - 2015-07-12
---------------------------------
* added Assertions for notNull and stringEmpty
* updated jar filters in Skb_Defaults
* added readFile to FileUtils
* added DirectoryScanner to utils
* moved standard categories from skb-categories to here
* moved all composite implementation from skb-composite to here
* added ReportManager from skb-commons
* added skb-collections as pacakge de.vandermeer.skb.base.utils.collections
  ** cleanup some of the utility classes
  ** created factory, transformation, filter classes
  ** moved Skb_CollectionUtils to the new package
  ** added all skb.collections classes as @since v0.0.5
* removed duplicated from Skb_TextUtils (now in new collections pacakge)
* moved ARRAY_TO_TEXT() from Skb_TextUtils to Skb_ArrayUtils
* changed to commons-lang3 version 3.4
* added commons-io dependency for file handling


v0.0.5 - feature add - 2015-06-23
---------------------------------
* added console utils
* moved encoding to console utils
* added jar and package filters for ExecS usage
* added net and thread uilities


v0.0.4 - maintenance - 2015-06-19
---------------------------------
* fixed artefact name, clean up, test file rename


v0.0.3 - feature add - 2015-06-18
---------------------------------
* added excludes to logback dependencies
* fixed msg init error in Skb_BaseException
* changed default message in Skb_BaseException
* added WRAP_LINES to Skb_TextUtils (from asciitable)


v0.0.2 - feature add - 2014-06-25
---------------------------------
* fixed javadoc problems (missing parameters)
* changed STGroup behaviour in Message5WH: added custom groups and group tests; removed static STGroup member


v0.0.1 - initial release - 2014-06-10
-------------------------------------
